### PR TITLE
Shadow DOM support

### LINKED ISSUE #28: Shadow DOM
#### Description
The Focus-ring Polyfill has some issues when used with shadow DOM. The Polyfill is not able to add the focus-ring class to focusable elements within the shadow DOM such as a buttons. This is due to the shadow DOM event model. Events bubble up from shadow DOM but the events are re-targeted. This means that the events look like they come from the host instead of its internal events within the shadow DOM.

#### Versions & Environment
Focus-ring: v1.0.1

#### Steps to Reproduce
- Clone repository `git@github.com:emilbillberg/focus-ring-shadow-dom.git`
- Start a local server such as live-server or similar
- The Polyfill is NOT able to set the focus-ring class on the button element
- Go to the index.html file and change the Polymer Global setting to `shady` instead of `shadow`
- The Polyfill is able to set the focus-ring class on the button element

#### Expected Results
The Polyfill should be able to set the focus-ring class on the button element when using Shadow DOM

#### Actual Results
The Polyfill sets the focus-ring class on the top custom element. In the example above this will be the custom element `my-app`.

### LINKED ISSUE #193: Is DOM ready necessary?
The only line that seems to depend on some sort of DOM readiness is:

```js
document.body.classList.add('js-focus-visible');
```

Could that be:

```js
document.documentElement.classList.add('js-focus-visible');
```

…so this script could be loaded lazily or async?

### PR DESCRIPTION
**Pull request by cdata**
# Shadow DOM support

This change enables custom elements to coordinate with the polyfill in order to apply it to discrete scopes of the composed tree (such as their shadow roots). Highlights include:

 - The polyfill is now exported to `window` as a function that can be invoked on any `Document|ShadowRoot`
 - The polyfill is automatically, synchronously applied to the top-level `document` when its script runs, preserving the existing behavior
 - Code that wishes to use the polyfill in a `ShadowRoot` can apply it as needed
   - Shadow hosts that have the polyfill applied are decorated with a `data-js-focus-visible` attribute
 - A `focus-visible-polyfill-ready` event is now dispatched on `window` to support lazy loading scenarios (see discussion in #193)

## Example usage as a mixin

In the course of implementing this proposal, I also crafted a mixin to demonstrate how a custom element should coordinate with the polyfill in order to take advantage of `:focus-visible`-like capabilities.

I am **not** proposing to include the mixin in the main project, but it is linked here for future reference:

https://github.com/cdata/focus-visible/blob/fc33395294dd69ad8af70e822e6176a8893816e2/src/custom-element-mixin.js#L1-L49

## Compared to #112 

There is an older WIP proposal (#112) up for consideration that attempts to add transparent support for arbitrary shadow roots. This approach would ultimately require that `focus` and `blur` be observed at every shadow boundary throughout the composed tree in order to work transparently.

The design in the proposal before you expects a Shadow DOM-using component author to opt-in to the polyfill. This allows the polyfill to be applied to Shadow DOM-using components that need it, while avoiding the cost of observing changes in shadow roots that do not know about or do not want to use the polyfill.

## Examples

For the purposes of the following examples:

 - `:focus` elements are styled with purple `color` and `border-color`
 - `:focus-visible` elements receive the default focus ring
 - Elements with shadow roots have `delegatesFocus: true` configured
 - Custom elements apply the [mixin](https://github.com/cdata/focus-visible/blob/fc33395294dd69ad8af70e822e6176a8893816e2/src/custom-element-mixin.js#L1-L49) referenced above to coordinate with the polyfill

This change w/ pointer traversal | This change w/ keyboard traversal
-------------------------------- | ----------------------------------
focus-not-visible | focus-visible

### Shadow root styling problem

Without this change, it is not possible to use the polyfill from within a shadow root. In the following example, you can see that the top-level document elements can be styled to hide the focus ring when focusing with pointer events, but focusable elements inside of a shadow root still display a focus ring:

Failure to style shadow root-encapsulated elements |
---------------------------------------------------- |
focus-not-visible-broken |

Fixes #193 
Fixes #28 
Fixes #112

### CODE REVIEW

File: src/focus-visible.js [hunk 1]
```diff
@@ -230,45 +234,57 @@ function init() {
...
+  if (scope.nodeType === Node.DOCUMENT_NODE) {
+    document.documentElement.classList.add('js-focus-visible');
 
-  if (['interactive', 'complete'].indexOf(document.readyState) >= 0) {
-    callback();
-  } else {
-    loaded = false;
-    document.addEventListener('DOMContentLoaded', load, false);
-    window.addEventListener('load', load, false);
+    // We detect that a node is a ShadowRoot by ensuring that it is a
```
Comment (alice) [inline src/focus-visible.js]: Putting this comment inside the previous if block is breaking my brain a little bit, though I can see why you did. Maybe switch the order of these if/else statements? It would be _marginally_ less efficient for the "normal" case, I guess, but more readable.

Or, perhaps a switch statement over `scope.nodeType` ?

File: test/specs/shadow-dom.js [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+  it('should apply .focus-visible on keyboard focus', async function() {
+    return matchesKeyboard();
+  });
+
+  it('should NOT apply .focus-visible on mouse focus', function() {
+    return matchesMouse(false);
+  });
+
+  describe('focusable elements in shadow', () => {
```
Comment (alice) [inline test/specs/shadow-dom.js]: Seems like this test is failing in CI for some reason.

**Comment by alice** [comment]
Generally looking really good (that gif blew my mind), not sure what's going on with that test though.

File: src/focus-visible.js (hunk 1 above)
Comment (cdata) [reply src/focus-visible.js]: Thanks @alice I'll try to rework this so that it is less of an eyesore

File: test/specs/shadow-dom.js (hunk 2 above)
Comment (cdata) [reply test/specs/shadow-dom.js]: Sorry about that, will take a look

**Comment by alice** [comment]
Just had a quick look into the test failure. Looks like it's failing in Firefox due to some interaction between the shady dom polyfill and the focus-visible polyfill.

**Comment by cdata** [comment]
I have addressed the test failures. The following changes were necessary:

 - In some browsers, we accessed the `content` of the inline `<template>` in the Shadow DOM test fixture too early. Deferring until `DOMContentLoaded` fixed the issue.
 - I had (mistakenly) assumed that the polyfill did not need to be applied at `shadowRoot` boundaries when the ShadyCSS polyfill was in effect. But, it turns out the polyfill does encapsulate focus events at the virtual shady root boundaries that it creates, so the `:focus-visible` polyfill should still be applied as normal.

File: src/focus-visible.js (hunk 1 above)
Comment (cdata) [reply src/focus-visible.js]: I switched the order of the conditions around. The comments are hopefully more cleanly formatted now.

**Comment by alice** [comment]
Aww, no commit history? We squash merge anyway.

**Comment by cdata** [comment]
Sorry, I will try to recreate the history

**Comment by alice** [comment]
Thanks and sorry :\

**Comment by cdata** [comment]
Nothing a little git gymnastics couldn't handle 👍

I split the change out into two commits. It looks like the Node.js 10 build had three test timeouts this time around. I'm not sure if that is actionable...

**Comment by alice** [comment]
Thanks so much for the git gymnastics! Build problems look like they were an infrastructure problem, it passed once I restarted it.

**Comment by cdata** [comment]
Thanks @alice ! BTW I should note before anyone merges this that due to the fix for #196 this should probably be considered a breaking change (albeit a small one). The timing around which the polyfill activates is different now, so it could break any user who is sensitive to that.

File: test/fixtures/shadow-dom.html [hunk 3]
```diff
@@ -36,18 +36,21 @@
...
+        el.attachShadow({ mode: 'open', delegatesFocus: true });
+        el.shadowRoot.appendChild(
+            shadowRootTemplate.content.cloneNode(true));
 
-      // If ShadyCSS is being used, there is no need to apply the polyfill to
-      // the shadow root because the shadow tree is not truly encapsulated:
-      if (self.ShadyCSS == null || self.ShadyCSS.nativeShadow) {
         applyFocusVisiblePolyfill(el.shadowRoot);
-      }
+      }, { once: true });
```
[the remark this answers is not in the document]
Comment (cdata) [reply test/fixtures/shadow-dom.html]: 🎉

**Comment by cdata** [comment]
@robdodson LMK if I can do anything to help move this one forward!

image

File: README.md [hunk 4]
```diff
@@ -95,6 +95,42 @@ You can use a service like [Polyfill.io](https://polyfill.io) to download only t
...
+### Shadow DOM
+
+It could be very expensive to apply this polyfill automatically to every shadow
+root that is created in a given document, so the polyfill ignores shadow roots
+by default. If you are using Shadow DOM in a component, it is possible to apply
+this polyfill imperatively to the component's shadow root:
+
+```javascript
+// Check for the polyfill:
+if (self.applyFocusVisiblePolyfill != null) {
```
Comment (robdodson) [inline README.md]: Is `self` equivalent to `window`? Not sure if the snippet makes it clear what context this is running in.

File: README.md [hunk 5]
```diff
@@ -95,6 +95,42 @@ You can use a service like [Polyfill.io](https://polyfill.io) to download only t
...
+When this polyfill is lazy-loaded, and you are applying the polyfill to a shadow
+root with JavaScript, it is important to know when the polyfill has become
+available before trying to use it.
+
+In order to act at the right time, you can observe the global
+`focus-visible-polyfill-ready` event:
+
+```javascript
+window.addEventListener('focus-visible-polyfill-ready',
+    () => self.applyFocusVisiblePolyfill(myComponent.shadowRoot),
```
Comment (robdodson) [inline README.md]: Similar to above, what's the expected value of `self` in this context?

File: README.md (hunk 4 above)
Comment (cdata) [reply README.md]: Yeah, `self` is equivalent to `window` in the document context. I can change this to `window`.

File: README.md (hunk 5 above)
Comment (cdata) [reply README.md]: Will change to `window`.

**Comment by robdodson** [comment]
I think this is good to merge once chris makes the `window` changes in the README.

**Comment by cdata** [comment]
@robdodson README has been updated per your request 🍻

File: src/focus-visible.js [hunk 6]
```diff
@@ -230,45 +234,58 @@ function init() {
...
-    callback();
-  } else {
-    loaded = false;
-    document.addEventListener('DOMContentLoaded', load, false);
-    window.addEventListener('load', load, false);
-  }
+try {
+  event = new CustomEvent('focus-visible-polyfill-ready');
+} catch (error) {
+  // IE11 does not support using CustomEvent as a constructor directly:
```
Comment (jakearchibald) [inline src/focus-visible.js]: Does it support `new Event()`?

Comment (cdata) [reply src/focus-visible.js]: Some very light Googling yields this [Stack Overflow](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work) that suggests "no" and "use CustomEvent instead"  😄
